# --- Ruby: Jekyll + gems, pinned reproducibly ----------------------------
# gemset.nix is generated by `bundix` (see the dev shell). Until it
# exists the expression still evaluates, so `nix develop` can run bundix
# to create it in the first place.
{ pkgs, ruby-nix }:
let
  rubyNix = ruby-nix.lib pkgs;
  gemset =
    if builtins.pathExists ../gemset.nix
    then import ../gemset.nix
    else { };
in
rubyNix {
  name = "aumitleon-github-io";
  ruby = pkgs.ruby_3_3;
  inherit gemset;
  gemConfig = pkgs.defaultGemConfig;
}
