# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://aumitleon.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Aumit Leon"
description: Software Engineer @ Spotify

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Aumit Leon
author-bio: Software Engineer @ Spotify  # change to false to hide
author-image: headshot.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Resume
  permalink: resume
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/aumitleon
facebook: false
instagram: false
github: https://github.com/AumitLeon
linkedin: https://www.linkedin.com/in/aumitleon/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Aumit Leon"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-YH9HHMVXP9

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
