{
  description = "aumitleon.github.io — Jekyll + Tailwind CSS, built with Nix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.11";
    flake-utils.url = "github:numtide/flake-utils";

    # Gems from Gemfile.lock, pinned via gemset.nix (below). ruby-nix builds
    # the gem environment; the inscapist bundix fork regenerates gemset.nix and
    # handles the platform-dependent gems in our lock (ffi, google-protobuf,
    # sass-embedded ship per-platform).
    ruby-nix.url = "github:inscapist/ruby-nix";
    bundix = {
      url = "github:inscapist/bundix/main";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, ruby-nix, bundix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        fs = pkgs.lib.fileset;

        # --- Ruby: Jekyll + gems, pinned reproducibly -------------------------
        # gemset.nix is generated by `bundix` (see the dev shell). Until it
        # exists the expression still evaluates, so `nix develop` can run bundix
        # to create it in the first place.
        rubyNix = ruby-nix.lib pkgs;
        gemset =
          if builtins.pathExists ./gemset.nix
          then import ./gemset.nix
          else { };
        rubyEnv = rubyNix {
          name = "aumitleon-github-io";
          ruby = pkgs.ruby_3_3;
          inherit gemset;
          gemConfig = pkgs.defaultGemConfig;
        };

        # --- Tailwind CSS -----------------------------------------------------
        # The standalone tailwindcss CLI: a single binary that bundles the
        # first-party plugins (including @tailwindcss/typography, which
        # tailwind.config.js pulls in) and autoprefixer. Replaces the old
        # node/yarn/PostCSS toolchain entirely.
        tailwindcss = pkgs.tailwindcss;

        # --- Vendored front-end assets (no runtime CDN) -----------------------
        # Everything the rendered pages load is served from the site's own
        # origin, so a visitor never depends on a third-party CDN and an
        # archived copy stays byte-identical. Each source is pinned by hash, so
        # this stays as reproducible as the rest of the build. (Google Analytics
        # in _includes/google-analytics.html is an intentional exception -- it
        # is an external call by nature and cannot be vendored.)

        # Inter, pinned to the exact rsms/inter web release that replaces the old
        # <link> to rsms.me. `stripRoot = false` keeps the archive's top-level
        # layout (multiple entries: web/, *.ttf, LICENSE...), and the served CSS
        # lives at web/inter.css referencing the flat web/*.woff2 next to it.
        # The families it defines are "InterVariable"/"Inter" -- see the sans
        # font stack in tailwind.config.js.
        inter-web = pkgs.fetchzip {
          url = "https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip";
          hash = "sha256-5vdKKvHAeZi6igrfpbOdhZlDX2/5+UvzlnCQV6DdqoQ=";
          stripRoot = false;
        };

        # Font Awesome 5.15.4 Free, the official web distribution (CSS +
        # webfonts). nixpkgs' `font-awesome` ships only desktop OTFs with no CSS
        # and at a different major version, so it can't drive web icons; we fetch
        # the exact release the site used to load from use.fontawesome.com.
        fontawesome = pkgs.fetchzip {
          url = "https://github.com/FortAwesome/Font-Awesome/releases/download/5.15.4/fontawesome-free-5.15.4-web.zip";
          hash = "sha256-nHPYOPTgSfkdyGNP7cxKsJ2AwVGcbynUZ8xQdAVORmI=";
          stripRoot = false;
        };

        # MathJax 3, the standard web bundle straight from nixpkgs (pinned via
        # the flake lock) -- the same major version the jsdelivr <script> used.
        # The es5/tex-mml-chtml.js entry point lazily loads sibling chunks and
        # fonts, so the whole es5/ tree is copied, not just that one file.
        mathjax = pkgs.nodePackages.mathjax;

        # Drop the vendored assets into ./assets/vendor next to the site tree.
        # Shared by the build's installPhase and the dev `serve` app so the
        # local dev server resolves the same local paths the built site uses.
        vendorAssets = dest: ''
          mkdir -p ${dest}/inter ${dest}/fontawesome ${dest}/mathjax
          cp -r ${inter-web}/web/. ${dest}/inter/
          cp -r ${fontawesome}/fontawesome-free-5.15.4-web/css \
                ${fontawesome}/fontawesome-free-5.15.4-web/webfonts ${dest}/fontawesome/
          cp -r ${mathjax}/lib/node_modules/mathjax/es5/. ${dest}/mathjax/
          chmod -R u+w ${dest}
        '';

        # Compile _styles/main.css -> the served stylesheet. Shared verbatim by
        # the build below and the dev workflow so both emit identical CSS.
        # Scans ./**/*.html (per tailwind.config.js `content`); run after
        # `jekyll build` it also sees the rendered pages under _site, so every
        # utility class actually used on the site is captured.
        tailwindBuild = out: ''
          ${tailwindcss}/bin/tailwindcss \
            --config ./tailwind.config.js \
            --input ./_styles/main.css \
            --output ${out} \
            --minify
        '';

        # --- The built site: `nix build` --------------------------------------
        site = pkgs.stdenv.mkDerivation {
          # Bare `name` (no version) so the store path ends in `aumitleon.dev`.
          name = "aumitleon.dev";

          # Explicit rather than `fileset.gitTracked` because that reads .git,
          # which the flake's source copy in the store does not carry. Lists the
          # inputs Jekyll (and the Tailwind pass) actually read.
          src = fs.toSource {
            root = ./.;
            fileset = fs.unions [
              ./_config.yml
              ./_layouts
              ./_includes
              ./_plugins
              ./_posts
              ./_styles
              ./assets
              ./legacy
              ./tailwind.config.js
              ./404.html
              ./CNAME
              ./about.md
              ./blog.md
              ./index.md
              ./projects.md
              ./tag.md
            ];
          };

          nativeBuildInputs = [ rubyEnv.env tailwindcss ];

          env = {
            JEKYLL_ENV = "production";
            # The sandbox ships no locale; without this Ruby tags subprocess
            # output as US-ASCII and the first multibyte char raises.
            LANG = "C.UTF-8";
            # The sandbox has no /etc/zoneinfo, so `timezone:` in _config.yml
            # would silently resolve to UTC.
            TZDIR = "${pkgs.tzdata}/share/zoneinfo";
            # _plugins/commit_hash.rb reads GITHUB_SHA for the footer's
            # "Improve this page" link. No .git in the sandbox, so the flake
            # supplies the revision it was built from: the commit when clean,
            # "<sha>-dirty" when the tree has uncommitted changes.
            GITHUB_SHA = self.rev or self.dirtyRev or "dirty";
            # _plugins/nix_store.rb surfaces this in the footer as the store path
            # the site was built into. `placeholder "out"` is rewritten to the
            # real $out in the build environment before jekyll runs, so the page
            # names its own store path without the hash being circular.
            JEKYLL_STORE_PATH = builtins.placeholder "out";
          };

          buildPhase = ''
            runHook preBuild
            jekyll build
            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall
            mkdir -p $out
            cp -r _site/. $out/
            mkdir -p $out/assets/css
            ${tailwindBuild "$out/assets/css/style.css"}
            ${vendorAssets "$out/assets/vendor"}
            runHook postInstall
          '';
        };

        # --- Local preview of the built site ----------------------------------
        # Serves the `site` derivation behind nginx with the same
        # `try_files $uri $uri.html` fallback GitHub Pages uses, so pretty URLs
        # like /about resolve to about.html -- which a dumb static server won't
        # do. This is what `nix build` produces, exactly as it will deploy.
        previewConf = pkgs.writeText "nginx-preview.conf" ''
          daemon off;
          error_log stderr info;
          pid /tmp/aumitleon-preview/nginx.pid;
          events {}
          http {
            include ${pkgs.nginx}/conf/mime.types;
            default_type application/octet-stream;
            access_log /dev/stdout;
            client_body_temp_path /tmp/aumitleon-preview/client;
            proxy_temp_path /tmp/aumitleon-preview/proxy;
            fastcgi_temp_path /tmp/aumitleon-preview/fastcgi;
            uwsgi_temp_path /tmp/aumitleon-preview/uwsgi;
            scgi_temp_path /tmp/aumitleon-preview/scgi;
            server {
              listen 8080;
              server_name localhost;
              root ${site};
              location / {
                try_files $uri $uri.html $uri/index.html =404;
              }
            }
          }
        '';
        preview = pkgs.writeShellScriptBin "preview" ''
          set -e
          mkdir -p /tmp/aumitleon-preview
          echo "🌍 Serving the Nix build at http://127.0.0.1:8080  (Ctrl-C to stop)"
          exec ${pkgs.nginx}/bin/nginx -c ${previewConf} -e /tmp/aumitleon-preview/error.log
        '';
      in
      {
        packages = {
          default = site;
          site = site;
        };

        # `nix develop` (or direnv): the impure, watch-friendly dev loop.
        devShells.default = pkgs.mkShell {
          TZDIR = "${pkgs.tzdata}/share/zoneinfo";
          buildInputs = [
            rubyEnv.env
            tailwindcss
            # Regenerates gemset.nix after a Gemfile/Gemfile.lock change.
            bundix.packages.${system}.default
            pkgs.git
          ];
          shellHook = ''
            echo "🚀 Jekyll + Tailwind — Nix dev shell"
            echo ""
            echo "  nix run .#serve      # live dev server (Tailwind --watch + jekyll serve)"
            echo "  nix build .#site     # pure, reproducible build -> ./result"
            echo "  nix run .#preview    # serve the built site via nginx (prod-like URLs)"
            echo "  bundix               # regenerate gemset.nix after a Gemfile change"
          '';
        };

        # `nix run .#serve`: compile CSS on change and serve a live Jekyll build.
        apps.serve = {
          type = "app";
          program =
            let
              serve = pkgs.writeShellScriptBin "serve" ''
                set -e
                export TZDIR="${pkgs.tzdata}/share/zoneinfo"
                # Vendored fonts/scripts (Inter, Font Awesome, MathJax) so the
                # dev server resolves the same local /assets/vendor paths the
                # built site uses -- otherwise those requests 404 in dev.
                echo "📦 Staging vendored assets -> assets/vendor"
                rm -rf ./assets/vendor
                ${vendorAssets "./assets/vendor"}
                # Compile once up front so the stylesheet exists before Jekyll's
                # first build -- otherwise the initial requests 404 on style.css
                # in the gap before the watcher's first pass finishes.
                echo "🎨 Compiling Tailwind CSS -> assets/css/style.css"
                ${tailwindcss}/bin/tailwindcss \
                  --config ./tailwind.config.js \
                  --input ./_styles/main.css \
                  --output ./assets/css/style.css \
                  --minify
                echo "🎨 Watching Tailwind CSS for changes"
                ${tailwindcss}/bin/tailwindcss \
                  --config ./tailwind.config.js \
                  --input ./_styles/main.css \
                  --output ./assets/css/style.css \
                  --minify --watch &
                tailwind_pid=$!
                trap "kill $tailwind_pid 2>/dev/null || true" EXIT
                exec ${rubyEnv.env}/bin/jekyll serve --host 0.0.0.0 "$@"
              '';
            in
            "${serve}/bin/serve";
        };

        # `nix run .#preview`: build the site and serve it behind nginx, with the
        # production `/about` -> about.html URL handling.
        apps.preview = {
          type = "app";
          program = "${preview}/bin/preview";
        };
      });
}
